### ISSUE TITLE
to-do

### ISSUE THREAD

**Issue by guisehn** [guisehn/elixir-text-based-fps#1]
- [x] exit room
- [x] exit previous room when joining room
- [x] exit server
- [ ] remove inactive players automatically
- [ ] remove inactive rooms automatically
- [x] callback to remove player when socket is disconnected
- [ ] remove room when everyone leaves
- [x] don't let user join same room they're already in
- [x] send notification when user joins room
- [ ] send notification when user changes their name
- [ ] send notification when user leaves room
- [ ] figure out how to restart agent if it crashes
- [x] notifications structure
- [x] add welcome message when connecting to socket instructing to set name, then choosing a room, etc.
- [x] web server with websockets
- [ ] tests
